### ISSUE TITLE
[question] How to for sure discard all changes that program did?

### ISSUE THREAD

**Issue by TuTAH1** [zhenyolka/DPITunnel-android#10]
In few days after installing PowerTunnel, Internet stopped working (from any source), the "proxy server refused connection" error showed up. I think PowerTunnel may be the reason of this issue. It take a very long time to stop it (in app), I think maybe it stopping incorrectly. Is there a way  to investigate it?

**Comment by zhenyolka** [comment]
My app called DPITunnel. PowerTunnel is an another dev's app. If I understand correctly, you used PowerTunnel for a while and now you want to give a try DPITunnel, right? Then just install it and run. This will fix the problem. If you want to delete DPITunnel after use, stop it firstly with button on app's dashboard screen. This action will remove DPITunnel's proxy from system settings.

**Comment by TuTAH1** [comment]
>If I understand correctly, you used PowerTunnel for a while and now you want to give a try DPITunnel, right?

No, I just mixed up apps names, sorry.

~~The problem is that turning off DPI Tunnel seems to not removes its proxy. Can I do that manually?~~

The problem is not actual anymore – I deleted DPI Tunnel, installed the new version of it and now it's works ok
