### ISSUE TITLE
Не подключается к HTTP серверу на андроиде

### ISSUE THREAD

**Issue by aire1** [zhenyolka/DPITunnel-android#11]
Использую SagerNet для подключения. Глобальный режим убрал, демон запускается, но подключения не происходит - все уходит в таймаут. Попробовал запустить DPITunnel-cli и подключиться, CA бандл пробовал указывать - там тоже самое, вывод такой: 
![image](https://user-images.githubusercontent.com/31969697/180472821-7b1a758a-7d31-4b22-aeca-39b9d0f6f85e.png)
Хочу использовать его в прокси-цепочке, но никак не могу заставить работать

Android 11, MIUI 12, POCO X3 NFC

**Comment by zhenyolka** [comment]
Почему-то происходит сброс соединения. Проблему ищи на том устройстве, где запущен dpitunnel. Возможно, ресурс заблокирован по ip. Не заблокированные ресурсы открываются?

**Comment by aire1** [comment]
Нет, вообще ничего не открывается. Сижу с вайфая, на компе с WSL Ubuntu все работает, а именно на телефоне — нет. Когда через приложение включен глобальный режим — все нормально, стоит выключить и подключаться вручную — такая вот фигня.

**Comment by aire1** [comment]
Также дополню, что DoH тоже не работает, вот вывод автоконфига:![IMG_20220722_220934_490.jpg](https://user-images.githubusercontent.com/31969697/180507627-01ce41c0-9d3a-4009-bc6c-2c6713b7f83c.jpg)

**Comment by zhenyolka** [comment]
Т.е. dpitunnel запущен в wsl, а подключение с телефона?? Почему тогда ip 127.0.0.1?

**Comment by aire1** [comment]
Нет. На WSL я тестировал отдельно, работает ли оно хотя бы на чистом линуксе, и ответ — да, работает. А вот на Андроиде уже нет (скрины кидал с Termux). Что вручную запускать cli версию, что приложение, к HTTP прокси коннекта нет. Работает только приложение и только в глобальном режиме

**Comment by zhenyolka** [comment]
Ну тогда проблема вот в чем. Если бинарник статический с гитхаба, то на андроиде проблема с dns, надо использовать опцию --builtin-dns, плюс я бы doh использовал. Я бы советовал в приложении отключить глобальный прокси, выбрать тип прокси http-прокси, запустить и дальше уже использовать, чтобы с термуксом не заморачиваться

**Comment by aire1** [comment]
Я так и пробовал в приложении изначально, результат тот же, только там в итоге сам инстанс dpitunnel-cli крашится, если пытаться подлючиться к HTTP прокси. Также и --builtin-dns тоже пробовал, вообще ноль эффекта, все то же самое. DoH через автоконфиг и вне него на андроиде не работает, обычный DNS, вроде как, работает, но все одно - connection aborted. На других устройствах проверить не могу, не на чем.

**Comment by zhenyolka** [comment]
Проблема в образовавшейся петле, т.е. циклического проксирования dpitunnel самого себя, из-за неправильной настройки SagerNet.
