### ISSUE TITLE
Maybe this will work with shizuku for non-rooted devices?

### ISSUE THREAD

**Issue by Wjxfi** [zhenyolka/DPITunnel-android#16]
https://github.com/RikkaApps/Shizuku

**Comment by zhenyolka** [comment]
Duplicate of #7. It is not issue.

**Comment by zhenyolka** [comment]
Shizuku is not replacement for root. Can you understand that raw sockets wont work without real root?

There are many people giving "useful" suggestions how to make it work without root. No one gave real solution yet, you aren't the first.
