### ISSUE TITLE
DoH does not work correctly with custom server

### ISSUE THREAD

**Issue by dit7ya** [zhenyolka/DPITunnel-android#6]
I could not get my custom DNS server endpoint to work - it either just uses Google or stops DNS to work altogether.

**Comment by zhenyolka** [comment]
@dit7ya many people uses DPITunnel with custom DoH servers from Cloudflare, quad, unpopular services. It works. Idk why it doesn't work for you. You don't give any details or explanation.

**Comment by dit7ya** [comment]
Please let me know what kind of information would be helpful and I will try to provide that. I am trying to use NextDNS.

**Comment by zhenyolka** [comment]
Give me screenshot of your profile with filled NextDNS address.
What does it mean don't work? Program can't start or sites don't open because of DNS?

**Comment by reforget-id** [comment]
Happened to me as well. I use NextDNS with configuration. It's worked if it without configuration.

https://dns.nextdns.io - work
https://dns.nextdns.io/c561d8 - doesn't work

![IMG_20220425_162640](https://user-images.githubusercontent.com/58993868/165061217-e975dfde-08d4-447b-a96a-ec855e636d66.jpg)

![Screenshot_20220425-161258797 (1)](https://user-images.githubusercontent.com/58993868/165060986-f611de49-4390-4c9a-b8ec-d98b59d33ea9.jpg)

**Comment by zhenyolka** [comment]
@dit7ya @reforget-id resolved in https://github.com/zhenyolka/DPITunnel-cli/commit/4a58c44d73c040e2c62abfd3d7654800f8e02237
