### ISSUE TITLE
Why does it require root?

### ISSUE THREAD

**Issue by fa1rid** [zhenyolka/DPITunnel-android#7]
Is it possible to make it work without root access?

**Comment by zhenyolka** [comment]
No, because it needs raw sockets to capture and inject packets. If you know how to create raw socket without root or any other way ro inject and capture packets, let me know.

**Comment by worstperson** [comment]
Should easy possible by chaining a vpn to socks app with an anti-DPI socks proxy.

https://github.com/bndeff/socksdroid
https://github.com/bol-van/zapret

tpws does not require root in socks mode. The static binaries provided do work on Android.

**Comment by zhenyolka** [comment]
@worstperson tpws is too limited. It can segment traffic only. DPI Tunnel allows you to send fake packets and use TCP disorder. For that purpose it needs raw sockets, that requires root access.

**Comment by zhenyolka** [comment]
@worstperson if you don't understand something, try to study it. Only after that you can start giving advices on the subject.
