### ISSUE TITLE
I uninstalled app but system proxy 8080 Therefore, it prevents all apps from accessing the Internet

### ISSUE THREAD

**Issue by hamedsbt** [zhenyolka/DPITunnel-android#8]
I uninstalled app but system proxy 8080 still remain!!! the WiFi icon has gray color with exclamation mark and prevent apps to access to Internet 
How I can remove http proxy 8080 forward? Can I use adb command to remove it ?

**Comment by zhenyolka** [comment]
DON'T REMOVE APP WHILE IT IS RUNNING!
Now install app again, press "start", then "stop" and wait for red background. After that uninstall app.

**Comment by hamedsbt** [comment]
Thank you for reply, The app don't response to stop button tap ( I'm waiting 2 min)
Can you help me to kill on remove file to remove system-wide proxy config? Does it create iptables rule? Does proxy config start/config on boot?

**Comment by zhenyolka** [comment]
It uses shell command to write to system settings. You can manually remove proxy. Run this command with root rights:
settings put global http_proxy :0

**Comment by hamedsbt** [comment]
It's better the Readme.txt file contains this issues & this fix.
