### ISSUE TITLE
Add a quick settings tile

### ISSUE THREAD

**Issue by RaafatTurki** [zhenyolka/DPITunnel-android#9]
Here's some visual aid to make sure we're all on the same page.
![image](https://user-images.githubusercontent.com/16624558/169027046-27dc0f8a-951d-4c29-932b-b5574f77095c.png)

Having a quick switch there makes it much faster to toggle, much needed when you have local services that don't work with DPITunnel.

**Comment by zhenyolka** [comment]
I have to close that as duplicate of #5. It's good suggestion, I will try to implement it in the next release.
